Repository wecode-bootcamp-korea/fullstack3-1st-wepleshop-frontend, pull requests merged in 2022-01, with the labels that each got.

#8 add: slide 구현중
  .gitignore
  package-lock.json
  public/index.html
  src/Router.js
  src/pages/flowcard/flowcard.scss
  src/pages/flowcard/folwcard.js
  src/pages/slide/carousel.js
  src/pages/slide/carousel.scss
  src/pages/slide/slide.js
  src/pages/slide/slide.scss
  src/pages/slide/slidecard.js
  src/pages/slide/slidecard.scss
Labels: Status: 추가 기능 구현 중

#9 Add : 디테일 페이지 구현 완료 (백엔드 연동중)
  package-lock.json
  package.json
  src/Router.js
  src/components/section/Section.js
  src/components/top/Top.js
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
  src/pages/Detail/ImageSlider.js
  src/pages/Detail/SingleComment.js
  src/pages/Detail/SliderData.js
  src/pages/home/Home.js
  src/pages/index.js
Labels: Status: 추가 기능 구현 중

#7 [Main] Product List Component
  package-lock.json
  package.json
  public/images/index.md
  src/Router.js
  src/config.js
  src/pages/ProductList/CategoryModal.js
  src/pages/ProductList/ItemCard.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: Status: 추가 기능 구현 중, Status: 피어 리뷰 요청

#16 Login 로직 수정
  src/components/modalLogin/ModalLogin.js
  src/components/modalLogin/ModalLogin.scss
  src/components/modalLogin/ModalPersonal.js
  src/components/modalLogin/ModalPersonal.scss
  src/components/modalLogin/ModalSignUp.js
  src/components/modalLogin/ModalSignUp.scss
  src/components/modalLogin/ModalTerms.js
  src/components/modalLogin/ModalTerms.scss
  src/components/nav/Nav.js
  src/pages/login/Login.js
  src/pages/login/LoginSignIn.js
  src/pages/login/LoginSignUp.js
Labels: Status: 피어 리뷰 요청

#23 Add: Product filtering
  public/images/clothes/item4/1.jpeg
  public/images/clothes/item4/2.jpeg
  src/pages/ProductList/CategoryModal.js
  src/pages/ProductList/ProductList.js
Labels: Status: 피어 리뷰 요청

#22 Add : 색상 사이즈 선택창 제품별 적용
  src/pages/Detail/ColorList.js
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
  src/pages/Detail/SizeList.js
  src/pages/ProductList/List.js
  src/pages/slide/slidecard.scss
Labels: Status: 피어 리뷰 요청

#28 [Login] 리팩토링(로그인 로직 개선)
  public/index.html
  src/pages/login/Login.js
  src/pages/login/Login.scss
  src/pages/login/LoginSignIn.js
  src/pages/login/LoginSignUp.js
  src/pages/login/modal/ModalEmail.js
  src/pages/login/modal/ModalLogin.js
  src/pages/login/modal/ModalLogin.scss
  src/pages/login/modal/ModalName.js
  src/pages/login/modal/ModalPassword.js
  src/pages/login/modal/ModalPersonal.js
  src/pages/login/modal/ModalPersonal.scss
  src/pages/login/modal/ModalSignUp.js
  src/pages/login/modal/ModalSignUp.scss
  src/pages/login/modal/ModalTerms.js
  src/pages/login/modal/ModalTerms.scss
Labels: Status: 피어 리뷰 요청

#29 Feature/cart
  src/Router.js
  src/components/top/Top.js
  src/components/top/TopDetail.js
  src/pages/Cart/Cart.js
  src/pages/Cart/CartBody.js
  src/pages/Cart/CartBody.scss
  src/pages/Cart/CartTop.js
  src/pages/Cart/CartTop.scss
Labels: Status: 추가 기능 구현 중, Status: 피어 리뷰 요청

#31 Feature/product list
  src/pages/ProductList/CategoryModal.js
  src/pages/ProductList/ItemCard.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/SortModal.js
  src/pages/ProductList/SortModal.scss
Labels: Status: 피어 리뷰 요청, Status: 컨플릭트 해결 요청

#35 Edit : 장바구니 프론트엔드 최종 적용
  README.md
  src/pages/Detail/ColorList.js
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
  src/pages/Detail/ImageSlider.js
  src/pages/Detail/SizeList.js
Labels: Status: 피어 리뷰 요청

#36 Add: mypage 로그인 token값을 이용한 사용자 이름 노출 구현
  src/Router.js
  src/components/nav/Nav.js
  src/config.js
  src/pages/login/Login.js
  src/pages/login/modal/ModalSignUp.js
  src/pages/mypage/Mypage.js
  src/pages/mypage/Mypage.scss
  src/pages/mypage/MypageLogin.js
  src/pages/mypage/MypageNotLogin.js
Labels: Status: 피어 리뷰 요청
